spring.application.name=PamyDex
spring.h2.console.enable=true #Ativa a interface web do H2
spring.h2.console.path=/h2.console #Url do console
spring.datasource.url=jdbc:h2:mem:pamydex #define o banco, mem -> banco em memoria
spring.jpa.show-sql=true #Imprime o sql executado no terminal (bom pra debug)
spring.jpa.hibernate.ddl-auto=create-drop #Defini oq fazer com as tabelas ao iniciar/parar (create-drop = criar/apaga)